### ISSUE TITLE
after success login (android), the webview not closed and show 404

### ISSUE THREAD

**Issue by teoprayoga** [eartho-group/one-client-flutter#3]
<img width="254" alt="Screen Shot 2022-11-19 at 00 17 13" src="https://user-images.githubusercontent.com/19910443/202751293-db69cbec-a824-401a-a359-47b3c8f24566.png">

**Comment by eartho-group** [comment]
Hi @teoprayoga . thanks for letting us know.
Please make sure the ids are well. you should have client id that you took from our website and access id that also from our creator dashboard.

**Comment by eartho-group** [comment]
@teoprayoga  any update?

**Comment by teoprayoga** [comment]
i run my flutter project on ios device and run this example (android, ios) too using client id, secret key and access id working fine. 

but not working on android on my project. 
i see the docs there is noting todo (android folder) in configuration when install eartho one so kept it default flutter android

**Comment by eartho-group** [comment]
please join our discord server, one of our supporters will help you
